<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="https://au1996.github.io/interview/css/index.css" />
  </head>
  <body>
    <p>
      <a href="https://www.ituring.com.cn/article/66566" target="_blank" rel="noopener noreferrer"
        >文章链接</a
      >
    </p>
    <script>
      function MyPromise(executor) {
        var state = 'pending' // 初始状态为 pending
        var value = undefined // 成功时的返回值
        var reason = undefined // 失败时的原因
        var onFulfilledCallbacks = [] // 存储成功态的回调函数
        var onRejectedCallbacks = [] // 存储失败态的回调函数

        function resolve(newValue) {
          if (state === 'pending') {
            state = 'fulfilled' // 状态转为成功态
            value = newValue // 保存成功的返回值
            for (var i = 0; i < onFulfilledCallbacks.length; i++) {
              onFulfilledCallbacks[i](value) // 依次执行成功态的回调函数
            }
          }
        }

        function reject(newReason) {
          if (state === 'pending') {
            state = 'rejected' // 状态转为失败态
            reason = newReason // 保存失败的原因
            for (var i = 0; i < onRejectedCallbacks.length; i++) {
              onRejectedCallbacks[i](reason) // 依次执行失败态的回调函数
            }
          }
        }

        try {
          executor(resolve, reject) // 执行传入的执行器函数
        } catch (error) {
          reject(error) // 如果执行器函数出错，将 Promise 状态置为 rejected
        }

        function then(onFulfilled, onRejected) {
          return new MyPromise(function (resolve, reject) {
            if (state === 'fulfilled') {
              try {
                var result = onFulfilled(value) // 执行成功态的回调函数
                resolve(result) // 将新 Promise 置为成功态
              } catch (error) {
                reject(error) // 如果执行成功态的回调函数时出错，将新 Promise 置为失败态
              }
            }
            if (state === 'rejected') {
              try {
                var result = onRejected(reason) // 执行失败态的回调函数
                resolve(result) // 将新 Promise 置为成功态
              } catch (error) {
                reject(error) // 如果执行失败态的回调函数时出错，将新 Promise 置为失败态
              }
            }
            if (state === 'pending') {
              onFulfilledCallbacks.push(function (val) {
                try {
                  var result = onFulfilled(val) // 执行成功态的回调函数
                  resolve(result) // 将新 Promise 置为成功态
                } catch (error) {
                  reject(error) // 如果执行成功态的回调函数时出错，将新 Promise 置为失败态
                }
              })
              onRejectedCallbacks.push(function (res) {
                try {
                  var result = onRejected(res) // 执行失败态的回调函数
                  resolve(result) // 将新 Promise 置为成功态
                } catch (error) {
                  reject(error) // 如果执行失败态的回调函数时出错，将新 Promise 置为失败态
                }
              })
            }
          })
        }

        function catchMethod(onRejected) {
          return then(null, onRejected) // 捕获失败态的回调函数
        }

        function finallyMethod(onFinally) {
          return then(
            function (val) {
              return MyPromise.resolve(onFinally()).then(function () {
                return val
              })
            },
            function (res) {
              return MyPromise.resolve(onFinally()).then(function () {
                throw res
              })
            }
          )
        }

        function all(promises) {
          return new MyPromise(function (resolve, reject) {
            var results = []
            var counter = 0
            for (var i = 0; i < promises.length; i++) {
              promises[i]
                .then(function (value) {
                  results[i] = value
                  counter++
                  if (counter === promises.length) {
                    resolve(results)
                  }
                })
                .catch(function (reason) {
                  reject(reason)
                })
            }
          })
        }

        function race(promises) {
          return new MyPromise(function (resolve, reject) {
            for (var i = 0; i < promises.length; i++) {
              promises[i]
                .then(function (value) {
                  resolve(value)
                })
                .catch(function (reason) {
                  reject(reason)
                })
            }
          })
        }

        return {
          then: then,
          catch: catchMethod,
          finally: finallyMethod,
          all: all,
          race: race,
        }
      }

      MyPromise.resolve = function (value) {
        return new MyPromise(function (resolve) {
          resolve(value)
        })
      }

      MyPromise.reject = function (reason) {
        return new MyPromise(function (resolve, reject) {
          reject(reason)
        })
      }
    </script>

    <script>
      new Promise((resolve, reject) => {
        setTimeout(() => {
          reject(3)
        }, 500)
      })
        .then(
          (res) => {
            console.log('Promise_result1', res)
          },
          (err) => {
            console.log('Promise_result2', err)
          }
        )
        .then((res) => {
          console.log('Promise_result3', res)
          throw Error('Promise_error')
        })
        .catch((err) => {
          console.log('Promise_catch', err)
        })
    </script>

    <script>
      new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve('------')
        }, 500)
      }).then((res) => {
        console.log(res)
      })
    </script>

    <script>
      new MyPromise((resolve, reject) => {
        setTimeout(() => {
          reject(3)
        }, 500)
      })
        .then(
          (res) => {
            console.log('result1', res)
          },
          (res) => {
            console.log('result2', res)
          }
        )
        .then((res) => {
          console.log('result3', res)
          throw Error('my_error')
        })
        .catch((err) => {
          console.log('catch', err)
        })
    </script>
  </body>
</html>
